- blockchain-scrapers/Dockerfile-ada
- blockchain-scrapers/cmd/ada/ada.go
- blockchain-scrapers/docker-compose.yml
I had to create an up to date Cardano docker image: https://github.com/eristoddle/cardano-explorer-docker
The go module calls the explorer api running in the docker image.
For https://github.com/diadata-org/api-golang/issues/19
> add docker-compose entry, docker file and go module for cardano ADA

- blockchain-scrapers/Dockerfile-eth
- blockchain-scrapers/cmd/eth/main.go
- blockchain-scrapers/docker-compose.yml
This pull request adds support for scraping ETH supply.
The application scans each block and calculates supply by computing the reward for each block. This is done so because the *uncle* rewards can't be estimated by block number alone.
Note:
1. The delta between this code and [etherscan](https://etherscan.io/stat/supply) is about 600 ETH
2. Function `getblockReward` must be updated if in future Ethereum changes their reward logic.
3. Functions `fetchSupplyFromStorage` and `storeSupplyToStorage` are stubs, they need to be implemented.  If these 2 are not implemented, the startup time for the application will get progressively slower.
> Adding ETH scraper

- dia/Config.go
- exchange-scrapers/cmd/scraper.go
- exchange-scrapers/config/exchange-scrapers.json
- exchange-scrapers/scrapers/SimexScraper.go
- This PR implement a new scraper into the code for Simex exchange.
- Since Simex does not seem to implement a Websocket, it uses REST API.
- I have created a support struct into the code, i did not want modify so much classic scraper object.
- For now i have added 14 pairs to json file, it seems there are not so much top pairs in this exchange.
Core
I tested the code into Mac OS environment, with go 1.10.3
Fixes #13
> implement Simex REST scraper

- dia/Config.go
- exchange-scrapers/config/exchange-scrapers.json
- exchange-scrapers/scrapers/APIScraper.go
- exchange-scrapers/scrapers/OKEx.go
- This PR add the scraper for OKEx exchange using websocket.
-  It includes the functions to reconnect to ws and subscribe again to all channels in case of connection error. This happens frequently.
- There could be a code error into dia/config.go in `GetConfig()` func, when it istantiates `configFileApi`, it should forgot `.json` at the end of string creating, right ? Every exchange scraper catch the error.
- I used UTC timestamp, it has created during runtime immediately after retrieve the order. I have not used the timestamp into response because it has only the hour, It could be ambiguous. I tested it and the max difference is 2 seconds.
Scraper Core
I tested the code in MAC OS environment using go 1.10.3
FIxes: #4
> add scraper for OKEx exchange

- dia/Config.go
- exchange-scrapers/config/exchange-scrapers.json
- exchange-scrapers/scrapers/APIScraper.go
- exchange-scrapers/scrapers/HuobiScraper.go
- This PR add a trade history scraper for Huobi Exchange.
- 30 crypto pairs added to `exchange-scrapers.json`
- I have used UTC timestamp instead of `ts` parameter retrieved from response because it is not a unix timestamp.The difference in time could be at most 2/3 seconds.
- The `id` parameter for each trade is a value more than `int64/uint64` in size, it causes an overflow. I have left the id in `float64` (example:1.884369602511794e+21)
Core Scraper
I tested the code in MacOS environment, using go version 1.10.3
Fixes: #3
> add Scraper for Huobi Exchange

- dia/Config.go
- exchange-scrapers/config/exchange-scrapers.json
- exchange-scrapers/scrapers/APIScraper.go
- exchange-scrapers/scrapers/LBankScraper.go
- This PR add a scraper for LBank Exchange.
- It uses a UTC timestamp calculate during runtime instead of that retrieved from response because there is no timezone specified. (I can change it without problems)
- It uses a hash of timestamp as `ForeignTradeID` because there is no trade `id` into response.
- Add 20 crypto pairs.
Exchange Scraper core
I tested it in Mac OS environment, using go 1.10.3 
FIxes: #1
> add scraper for LBank Exchange

- dia/Config.go
- exchange-scrapers/config/exchange-scrapers.json
- exchange-scrapers/scrapers/APIScraper.go
- exchange-scrapers/scrapers/GateIOScraper.go
- This PR adds a scraper for GateIO Exchange.
- Add 25 pairs.
- The logic is little different, It needs only one subscribtion to `ws`,  it pass all pairs as parameters.
Exchange Scraper core
- I tested the code in Mac OS environment, using go1.10.3
Fixes: #45
> add scraper for GateIO Exchange

- cmd/services/pairDiscoveryService/main.go
I forgot the call to the `s.close()` function. Sorry
> FIX minor bug in pair Discovery Service

- config/Bittrex.json
- deployments/docker-compose.exchange-scrapers.yml
- internal/pkg/exchange-scrapers/APIScraper.go
- internal/pkg/exchange-scrapers/BittrexScraper.go
- pkg/dia/Config.go
- This PR adds a scraper for Bittrex Exchange (Rest API for now).
- It includes 50 pairs.
- It seems that in Bittrex the order of base currency into pair name is inverted. I left as other exchanges in config json, the pair name swaps in code.
- It does 60 API calls per minute (the limit for Bittrex). It can be resolved in the future with ws implementation.
Fixes: #94
> add scraper for bittrex exchange

- internal/pkg/exchange-scrapers/APIScraper.go
- internal/pkg/exchange-scrapers/UniswapV2Scraper.go
- pkg/dia/Config.go
Sushiswap cannot be added  in lending and buying structure of defi, there will be need of creating structure for farming pools.
This PR takes care of scrapping sushiswap exchange
https://exchange.sushiswapclassic.org/#/swap
> Add sushiswap exchange scrapper

- config/CREX24.json
- go.mod
- internal/pkg/exchange-scrapers/APIScraper.go
- internal/pkg/exchange-scrapers/CREX24Scraper.go
- pkg/dia/Config.go
Dear all, 
the CREX24Scraper works fine now as far as I can see. 
Please have a look at this and give it a try.
I am a bit unsure about the correct usage of the `dia.Pair` struct. I am currently simply taking the response from the [CREX24 API ](https://api.crex24.com/v2/public/instruments) and I'm mapping the values like this: 
```golang
dia.Pair{
Symbol:      parsedPairs[i].BaseCurrency,
ForeignName: parsedPairs[i].Symbol,
Ignore:      false,
Exchange:    s.exchangeName,
}
```
**Architecture:** There is one bidirectional signalR connection to CREX24. After subscribing for a trade pair by sending a message, CREX24 will send trade updates over this connection to the Scraper. The Scraper maps them to `dia.Trade` and sends them into the go channel. 
I chose to not initialize the …
> Adding a exchange scraper for CREX24

- internal/pkg/nftTrade-scrapers/cryptopunks.go
#408 
This PR will fix two mentioned problems in the original PR.
Here are my solutions:
> 1. For the initial run, you get the error: "error filtering FilterPunkBought: query returned more than 10000 results". So I'm afraid we'll have to fetch these in smaller chunks.
Now I'm using a sliding window of block ranges and it will reduce the window size by half whenever a limit error occurred.
> The trading data does not seem to be correct. The prices seem off and I think you're also fetching offers (price: 0 and to address zero address). See two examples below (I added the etherscan links to the transactions for your convenience).
Actually looks like that the txhash for the second mentioned event is `0xe5ba2e2ce07749beaddd15ad2ec2b30e678139ac76da88056588cf8055d441c0` and not …
> Fix the query limit issue for The CryptoPunks trade scraper

- config/verifiedSymbols/verifiedSymbols.json
Submission for gitcoin bounty: [Identify Exchange Symbol Ticker - HitBTC 1.3](https://gitcoin.co/issue/diadata-org/diadata/474/100026279).
Adds my handle to verifiedSymbols.json for HitBTC batch 1.
Closes #474.
> Identify Exchange Symbol Ticker - HitBTC 1.3

- config/verifiedSymbols/verifiedSymbols.json
Submission for gitcoin bounty: [Identify Exchange Symbol Ticker - HitBTC 2.2](https://gitcoin.co/issue/diadata-org/diadata/482/100026339).
Adds my handle to verifiedSymbols.json for HitBTC batch 1.
Closes #482.
> Identify Exchange Symbol Ticker - HitBTC 2.2

- config/FTX.json
- go.mod
- go.sum
- pkg/dia/Config.go
- pkg/dia/scraper/exchange-scrapers/APIScraper.go
- pkg/dia/scraper/exchange-scrapers/FTXScraper.go
- To add a new FTX scraper in diadata and the request originated from https://gitcoin.co/issue/diadata-org/diadata/505/100027344 and https://github.com/diadata-org/diadata/issues/505
- Add FTX exchange to the config file
- Implement FTX Scraper
> Add ftx exchange scraper

- cmd/nftTradescrapers/main.go
- config/nftContracts/openseaseaport/openseaseaport.go
- pkg/dia/nft/nftTrade-scrapers/openseaSeaport.go
This PR provides new NFT trade scraper that scrapes trades from Opensea's new Seaport 1.1 contract. It manages trades that involve new multi-asset trade between two parties (more information about this sytem [here](https://opensea.io/blog/announcements/launching-seaport-saving-the-community-millions-in-fees/)
None
* [Seaport's github](https://github.com/ProjectOpenSea/seaport)
* [Seaport's contract]( https://etherscan.io/address/0x00000000006c3852cbef3e08e8df289169ede581)
- Running scraper is hard and needs many extra steps, while the process itself isn't directly documented anywhere in the project
None
> NFT Trades Scraper for Seaport Opensea contract on Ethereum

- config/BitMart.json
- config/exchanges/exchanges.json
- config/gitcoinverified/BitMart.json
- pkg/dia/Config.go
- pkg/dia/scraper/exchange-scrapers/APIScraper.go
- pkg/dia/scraper/exchange-scrapers/BitMartScraper.go
Adds BitMart exchange scraper, this closes issue [Write A Trades Scraper For BitMart Exchange #627](https://github.com/diadata-org/diadata/issues/627).
* Config files for updated markets and exchange;
* `config/exchanges/exchanges.json`
* `config/BitMart.json`
* `config/gitcoinverified/BitMart.json`
* Scraper config (`pkg/dia/Config.go`) and interface file (`pkg/dia/scraper/exchange-scrapers/APIScraper.go`) ;
* Scraper `pkg/dia/scraper/exchange-scrapers/BitMartScraper.go`;
Signed-off-by: Alexandre Ferreira <alexjorgef@protonmail.com>
> Add BitMart exchange scraper

- pkg/dia/service/assetservice/source/serum.go
- pkg/dia/service/assetservice/source/serum_test.go
Add the solana endpoint to get token_names.
We can verify the functionality with the tests in pkg/dia/service/assetservice/source/serum_test.go
> fix: add rpc_endpoint_solana to get token_names

- cmd/nftTradescrapers/main.go
- config/nftExchanges/nftexchanges.json
- pkg/dia/Config.go
- pkg/dia/nft/nftTrade-scrapers/blurV1.go
This PR is the implementation of [this bounty](https://app.dework.xyz/dia-dao/dia-tech-guild?taskId=a5b21adc-619a-4f49-a138-b0838bb1fd69).
I followed the docs [here](https://github.com/diadata-org/diadata/blob/master/documentation/tutorials/nfttradescrapers.md) for testing locally.
I had to add the following line to the `cmd/nftTradescrapers/go.mod`:
```
replace github.com/diadata-org/diadata => [absolute path of the repo]
```
otherwise, the codes in `pkg` directory wouldn't be synced, I'm not really familiar with this monorepo architecture, so had to get around that by changing the go.mod file.
> feat: add blurv1 scraper

- pkg/dia/scraper/exchange-scrapers/BitfinexScraper.go
The default Bitfinex WebSocket connection prints debug messages. This changes the severity of the logs, removing annoying logs from the scraper
> remove debug logs from Bitfinex scraper
