diadata-org/diadata

blockchain-scrapers/Dockerfile-neo, blockchain-scrapers/cmd/neo/neo.go, blockchain-scrapers/docker-compose.yml
Once the neonode service is started It fetches the chain.acc.zip(3.6GB) only for the first time the docker is run, if saved file is not used then it takes days to sync the chain. volume is mounted from /home/srv/neo So data  is saved in this location and docker can be stopped and started and the chain will continue from before block.
Once the neo service is started it makes connection to the neonode service and  waits for the chain to sync, once the chain is synchronized it fetches neo at address AQVh2pG732YvtNaxEGkQUei3YA4cvo7d2i and substracts it from 100000000 and sends the supply to dia client
=> Neo Blockchain Scrapper

blockchain-scrapers/blockchains/eos/docker-compose.yml, blockchain-scrapers/blockchains/eos/node/Dockerfile, blockchain-scrapers/blockchains/eos/node/Dockerfile-node, blockchain-scrapers/blockchains/eos/scrapers/eos.go
This is an updated Scraper that reflects the changes that were made from #43.
If you have any questions or feedback.
Please let me know.
Also, since it would be extremely difficult to do continuous integration testing for this project with Travis... Perhaps maybe a server (or servers) with significant file storage space may be more suitable for unit testing.
=> Refactored EOSIO Scraper

README.md
I just fixed a few typos on the readme.
=> typos fixed.

internal/pkg/filtersBlockService/FilterMA.go, internal/pkg/filtersBlockService/FilterMA_test.go
@frranck  Added a test and fixed issue #78.
=> Fix issue #78

internal/pkg/exchange-scrapers/HuobiScraper.go
The scraper for this exchange is not properly terminating when `Close()` is called.
This PR partially addresses issue #118
=> Properly terminate mainLoop routine when Close() is called in HuobiScraper 

internal/pkg/exchange-scrapers/CoinBaseScraper.go, internal/pkg/exchange-scrapers/GateIOScraper.go, internal/pkg/exchange-scrapers/HitBTCScraper.go, internal/pkg/exchange-scrapers/LBankScraper.go, internal/pkg/exchange-scrapers/OKExScraper.go, internal/pkg/exchange-scrapers/QuoineScraper.go, internal/pkg/exchange-scrapers/SimexScraper.go, internal/pkg/exchange-scrapers/ZBScraper.go, pkg/dia/Config.go
This PR close #118 and closes #119
=> Implemented Close() for all remaining exchanges

internal/pkg/exchange-scrapers/OKExScraper.go
- This PR updates OKEx websocket url.
- From now it uses data compression.
- Every 15/20 minutes the ws close the connection and it needs to reconnect and subscribe again all pairs, it happened at time of my first OKEx PR too. In this way very few data could be lost.
Tested on mac os using go 1.10.3
FIxes: #131
=> update OKEx ws url and add data compression

contracts/DIAToken.sol, contracts/Dispute.sol, package.json, scripts/deployContracts.sh, test/Dispute.js, truffle-config.js
=> (WIP) Solidity

README.md
Pic taken out in technical introduction
=> Pic taken out in technical introduction

internal/pkg/defiscrapers/DefiScraper.go, internal/pkg/defiscrapers/updateAAVE.go, internal/pkg/defiscrapers/updateDYDX.go, pkg/utils/downloadResource.go
https://github.com/diadata-org/diadata/issues/222
=> update aave scrapper

internal/pkg/defiscrapers/DefiScraper.go, internal/pkg/defiscrapers/updateRAY.go
=> add ray loan protocol

internal/pkg/defiscrapers/DefiScraper.go, internal/pkg/defiscrapers/updateDharma.go
=> add dharma

internal/pkg/defiscrapers/DefiScraper.go, internal/pkg/defiscrapers/interface.go, internal/pkg/defiscrapers/updateAAVE.go, internal/pkg/defiscrapers/updateDYDX.go
Refactor DefiScrapper, 
```
type DeFIHelper interface {
UpdateRate() error
UpdateState() error
}
```
To add a new Scrapper simple create DeFIHelper, define UpdateRate and UpdateState
=> refactor scrappers as per DeFIHelper inteface

internal/pkg/defiscrapers/DefiScraper.go, internal/pkg/defiscrapers/interface.go, internal/pkg/defiscrapers/updateAAVE.go, internal/pkg/defiscrapers/updateDDEX.go, internal/pkg/defiscrapers/updateDYDX.go
https://github.com/diadata-org/diadata/issues/224
=> Defi Lending Rate Scraper for DDEX

internal/pkg/defiscrapers/DefiScraper.go, internal/pkg/defiscrapers/interface.go, internal/pkg/defiscrapers/updateAAVE.go, internal/pkg/defiscrapers/updateCompond.go, internal/pkg/defiscrapers/updateDYDX.go
https://gitcoin.co/issue/diadata-org/diadata/220/4523
=> Defi Lending Rate Scraper For Compound

internal/pkg/exchange-scrapers/APIScraper.go, internal/pkg/exchange-scrapers/UniswapScraper.go, pkg/dia/Config.go
https://github.com/diadata-org/diadata/issues/252
=> exchange scraper for Uniswap V2 DEX

internal/pkg/defiscrapers/DefiScraper.go, internal/pkg/defiscrapers/updateNUO.go
https://github.com/diadata-org/diadata/issues/233
=> Defi Lending Rate Scraper For Nuo Network

config/Loopring.json, internal/pkg/exchange-scrapers/APIScraper.go, internal/pkg/exchange-scrapers/LoopringScraper.go, pkg/dia/Config.go
https://github.com/diadata-org/diadata/issues/255
=> Exchange Scraper For Loopring DEX

internal/pkg/exchange-scrapers/BalancerScraper.go, internal/pkg/exchange-scrapers/balancer/balancerfactory/balancerfactory.go, internal/pkg/exchange-scrapers/balancer/balancerpool/balancerpool.go, internal/pkg/exchange-scrapers/balancer/balancertoken/balancertoken.go, internal/pkg/exchange-scrapers/balancer/src/BColor.sol, internal/pkg/exchange-scrapers/balancer/src/BConst.sol, internal/pkg/exchange-scrapers/balancer/src/BFactory.sol, internal/pkg/exchange-scrapers/balancer/src/BMath.sol, internal/pkg/exchange-scrapers/balancer/src/BNum.sol, internal/pkg/exchange-scrapers/balancer/src/BPool.sol, internal/pkg/exchange-scrapers/balancer/src/BToken.sol
=> Switch Balancer DEX Scraper to Infura

internal/pkg/defiscrapers/DefiScraper.go, internal/pkg/defiscrapers/fortubev2/fortubev2.go, internal/pkg/defiscrapers/fortubev2/token/token.go, internal/pkg/defiscrapers/updateForTube.go
=> add fortube defi scraper

internal/pkg/exchange-scrapers/CurvefiScraper.go, internal/pkg/exchange-scrapers/curvefi/curvefi.go, internal/pkg/exchange-scrapers/curvefi/curvefi.vy, internal/pkg/exchange-scrapers/curvefi/curvepool/curvepool.go, internal/pkg/exchange-scrapers/curvefi/token/token.go
=> switch curvefi scraper to infura

internal/pkg/exchange-scrapers/GnosisScraper.go, internal/pkg/exchange-scrapers/gnosis/gnosis.go, internal/pkg/exchange-scrapers/gnosis/token/token.go
=> switch gnosis scraper to use infura api

internal/pkg/exchange-scrapers/APIScraper.go, internal/pkg/exchange-scrapers/DforceScraper.go, internal/pkg/exchange-scrapers/dforce/dforce.go, internal/pkg/exchange-scrapers/dforce/token/token.go, pkg/dia/Config.go
=> add dforce exchange scraper

cmd/services/tokenService/main.go, internal/pkg/tokenService/erc20.go, internal/pkg/tokenService/tokenContract.go, pkg/model/TokenType.go, pkg/model/db.go, pkg/model/token.go
This is Token Service. Please test and comment.
=> Add tokenService

internal/pkg/exchange-scrapers/APIScraper.go, internal/pkg/exchange-scrapers/ZeroxScraper.go, internal/pkg/exchange-scrapers/zerox/token/token.go, internal/pkg/exchange-scrapers/zerox/zerox.go, pkg/dia/Config.go
=> add 0x exchange scraper

internal/pkg/exchange-scrapers/APIScraper.go, internal/pkg/exchange-scrapers/KyberScraper.go, internal/pkg/exchange-scrapers/kyber/kyber.go, internal/pkg/exchange-scrapers/kyber/token/token.go, pkg/dia/Config.go
=> add kyber exchange scraper

cmd/foreignscraper/foreign.go, deployments/docker-compose.foreignscraper.yml, internal/pkg/foreign-scrapers/CoinMarketCapScraper.go
=> add coinmarketcap quotation scraper

internal/pkg/exchange-scrapers/GateIOScraper.go, internal/pkg/exchange-scrapers/LoopringScraper.go, internal/pkg/exchange-scrapers/OKExScraper.go, internal/pkg/exchange-scrapers/QuoineScraper.go, internal/pkg/exchange-scrapers/ZBScraper.go
[] GateIO
[] loopring
[] Quoine (liquid)
[]  ZB
=> fix crashing exchange scrappers

.github/ISSUE_TEMPLATE/write-an-nft-scraper.md, internal/pkg/nftData-scrapers/sorare.go
Here is the proposed solution.
I'll be happy to improve it in case you have any feedback.
=> Write an NFT Scraper for Sorare - issue #390

cmd/nftTrade-scrapers/main.go, config/nftContracts/erc20/erc20.go, config/nftContracts/erc20/erc20.sol, config/nftContracts/erc721/erc721.go, config/nftContracts/erc721/erc721.sol, config/nftContracts/opensea/contract.go, config/nftContracts/opensea/contract.sol, deployments/config/pginit.sql, go.mod, go.sum, internal/pkg/nftTrade-scrapers/init.go, internal/pkg/nftTrade-scrapers/opensea.go, pkg/dia/Messages.go, pkg/model/nfts.go, pkg/model/relDB.go, pkg/model/scrapers.go, pkg/utils/ethtxfilter.go
first effort for opensea scraper
=> #413: added opensea trade scraper

internal/pkg/nftTrade-scrapers/cryptokitties.go
Hi @jppade  
I have added code for NFT trade scraper for cryptokitties addressing: #418 
Please review it and let me know of any changes.
Thanks
=> write an NFT trade scraper for cryptokitties

config/gitcoinverified/Binance_slightlyskepticalpotat.json
This PR is for the following bounty: https://gitcoin.co/issue/diadata-org/diadata/423/100026102
If there are any issues, please let me know and I will fix them right away. 
Please note that the following symbol changes have been made since they were changed on Binance:
- SNM is now SONM
- STRAT is not STRAX
- XZC is now FIRO
=> Add Binance Data

config/gitcoinverified/Binance_ControlCplusControlV.json
This is my completed work from the bounty. Let me know if you need to make any changes, I left 6 comments on some tokens I wasn't sure how to act on, to notify if the address shown was of a a migrated token (I showed the final migrated token but the old symbol), or if it was a duplicate ticker that pointed back to another coin already listed! Made for this [bounty](https://gitcoin.co/issue/diadata-org/diadata/424/100026103)
=> Added in Binance Tokens for Bounty

config/verifiedSymbols/verifiedSymbols.json
For GitCoin Bounty: https://gitcoin.co/issue/diadata-org/diadata/435/100026196
=> Add Name to PR

config/verifiedSymbols/verifiedSymbols.json
For gitcoin bounty: https://gitcoin.co/issue/diadata-org/diadata/438/100026200 (#438)
=> Add name - GateIO 1

config/verifiedSymbols/verifiedSymbols.json
Done for: https://gitcoin.co/issue/diadata-org/diadata/455/100026238
=> Add Name To Bittrex

config/verifiedSymbols/verifiedSymbols.json
Done for Bounty: https://gitcoin.co/issue/diadata-org/diadata/452/100026236
=> Add Name for OKEx

config/verifiedSymbols/verifiedSymbols.json
Closes #459 
Submission for the bounty of the same name. Adds my handle to KuCoin batch 2.
=> Identify Exchange Symbol Ticker - Kucoin 2.1

config/verifiedSymbols/verifiedSymbols.json
=> Exchange Symbol Ticker - Kucoin 2.2 

config/verifiedSymbols/verifiedSymbols.json
Closes #476 
Submission for the bounty of the same name. Adds my handle to Quoine.
=> Identify Exchange Symbol Ticker - Quoine 2

config/verifiedSymbols/verifiedSymbols.json
Done for: https://gitcoin.co/issue/diadata-org/diadata/477/100026282
=> Identify Exchange Symbol Ticker - Quoine 3

internal/pkg/stock-scrapers/finage.go
* Connecting to the web socket URL
* Scraping the stock quotations
=> Implement connection and scraping logic for finage

config/verifiedSymbols/verifiedSymbols.json
Done for Bounty: https://gitcoin.co/issue/diadata-org/diadata/483/100026340
Closes #483
=>  Identify Exchange Symbol Ticker - HitBTC 2.3

.gitignore, cmd/nftTrade-scrapers/main.go, internal/pkg/nftTrade-scrapers/nbatopshot.go
=> setup NBATopshot trade scraper

config/verifiedSymbols/verifiedSymbols.json
Closes #481
Submission for the bounty of the same name. Adds my handle to HitBTC batch 2.
=>  Identify Exchange Symbol Ticker - HitBTC 2.1

config/verifiedSymbols/verifiedSymbols.json
I added my name, verified for Quoine exchange as part of Identify Exchange Symbol Ticker - Quoine 1
=> 0xGlacier for Quoine

internal/pkg/nftTrade-scrapers/nbatopshot.go
Write a Trades Scraper for NBA Topshot NFTs #414
add new feature: add nft buyer address on every trade
=> handle nft Deposit event for every transaction

go.mod, internal/pkg/assetservice/source/serum.go
* Fetch all the asset pairs from the Serum Dex program (https://github.com/project-serum/serum-dex)
* Fetch all the `.token` accounts registered in the name-service program (https://spl.solana.com/name-service). This contains all the metadata about the token
* Create `dia.Asset` using the data and feed them to channels
https://github.com/diadata-org/diadata/issues/501
=> Add fetch assets for serum

config/verifiedSymbols/verifiedSymbols.json
Please refer : https://github.com/diadata-org/diadata/issues/524
=> sm67nono : Update to verified Symbols for ByBit

config/verifiedSymbols/verifiedSymbols.json
https://gitcoin.co/issue/diadata-org/diadata/523/100027522 <- For that Gitcoin Bounty
=> Added name for Verification of ByBit exchange

config/Bitforex.json, pkg/dia/Config.go, pkg/dia/scraper/exchange-scrapers/APIScraper.go, pkg/dia/scraper/exchange-scrapers/Bitforex.go
- To add a new Bitforex scraper in diadata and the request originated from https://gitcoin.co/issue/diadata-org/diadata/515/100027462 and https://github.com/diadata-org/diadata/issues/515
- Add Bitforex exchange to the config file
- Implement Bitforex Scraper
=> Add bitforex scraper

config/BitMex.json, pkg/dia/Config.go, pkg/dia/scraper/exchange-scrapers/APIScraper.go, pkg/dia/scraper/exchange-scrapers/BitMexScraper.go
Adds BitMex scraper implementation. 
Closes issue #516
=> Add bitmex scrapper

deployments/local/exchange-scraper/docker-compose.yml, deployments/local/exchange-scraper/local.env, documentation/tutorials/exchangescrapers.md
This will:
- add a docker-compose for local deployment of the exchange scraper
- Update the contribution guide for running an exchange scraper
=> Update the instructions for writing an exchange scraper 

cmd/http/restServer/restServer.go, pkg/dia/Messages.go, pkg/http/restServer/diaApi/diaApi.go, pkg/model/db.go
https://rest.diadata.org/v1/assetMarkets/Bitcoin/0x000000000000000000000000000000000000000
=> Endpoint to display volume per exchange 

config/nftContracts/looksrare/contract.go, config/nftContracts/looksrare/contract.sol, pkg/dia/nft/nftTrade-scrapers/looksrare.go
Closes #548, It's based on OpenSea trades scraper.
@jppade, please let me know if you need any thing else.
=> adds looksrare nft trades scraper

cmd/exchange-scrapers/collector/collector.go, cmd/exchange-scrapers/collectorTextOnly/scraper.go, config/BinanceUS.json, pkg/dia/Config.go, pkg/dia/scraper/exchange-scrapers/APIScraper.go, pkg/dia/scraper/exchange-scrapers/BinanceScraperUS.go
Created a BinanceUS struct that contacts the api.binance.us backend. Not really sure if it works, but it does build and run. More testing info and dev enviroment config would be useful, also not sure if I should PR this to the master branch.
=> add binance.us api scraper

cmd/nftTradescrapers/main.go, config/nftContracts/tofunft/tofunft.go, pkg/dia/nft/nftTrade-scrapers/tofunft.go
Add TofuNFT trade scraper for Astar network
=> Add tofunft trade scraper (Astar network)

pkg/dia/scraper/exchange-scrapers/BitmaxScraper.go
Signed-off-by: Alexandre Ferreira <alexjorgef@protonmail.com>
=> fix: Bitmax exchange name change, new url for api endpoint.

cmd/nftTradescrapers/main.go, pkg/dia/nft/nftTrade-scrapers/x2y2.go
=> feat: Add x2y2 nft scraper

deployments/docker-compose.services.yml, documentation/tutorials/README.md, documentation/tutorials/nfttradescrapers.md, pkg/dia/helpers/configCollectors/configCollectors.go
Steps to run an nft trade scraper locally.
=> docs: Add the nft trade scraper tutorial

config/MEXC.json, config/exchanges/exchanges.json, config/gitcoinverified/MEXC.json, pkg/dia/Config.go, pkg/dia/scraper/exchange-scrapers/APIScraper.go, pkg/dia/scraper/exchange-scrapers/MEXCScraper.go
Added MEXC scraper
Let me know if there is something todo more.
=> feat: MEXC scraper

go.mod, pkg/dia/nft/nftTrade-scrapers/magiceden.go
* update solana sdk module
* enable historical scraper through config
* creation time for nft
=> patch for magiceden issues

go.mod, pkg/dia/scraper/exchange-scrapers/LBankScraper.go
This fixes #656.
The `ping` message is not strictly necessary, I can also remove it completely.
=> LBank: fix `ping` message

cmd/assetCollectionService/main.go, go.mod, go.sum, pkg/dia/scraper/exchange-scrapers/OrcaScraper.go, pkg/dia/scraper/liquidity-scrapers/OrcaScraper.go, pkg/dia/scraper/liquidity-scrapers/ScraperInterface.go, pkg/dia/service/assetservice/source/orca.go
* change token metadata function to static
Signed-off-by: Alexandre Ferreira <alexjorgef@protonmail.com>
=> feat: add Orca liquidity provider

pkg/dia/scraper/foreign-scrapers/YahooFinanceScraper.go
Fixes the Yahoo Finance foreign collector
---
Arguments to test: `YAHOOFIN_CURRENCIES_MAP=EURTZS=X:EUR-TZS,EURTRY=X:EUR-TRY,USDTZS=X:USD-TZS,USDTRY=X:USD-TRY,USDNGN=X:USD-NGN,USDBRL=X:USD-BRL,USDAED=X:USD-AED,USDTWD=X:USD-TWD,USDARS=X:USD-ARS foreignscraper -foreignType=YahooFinance`
Output:
```sh
root@scraper-foreign-example-yahoofinance:/go/src# go mod tidy -go=1.16 && go mod tidy -go=1.17 && go install && YAHOOFIN_CURRENCIES_MAP=EURTZS=X:EUR-TZS,EURTRY=X:EUR-TRY,USDTZS=X:USD-TZS,USDTRY=X:USD-TRY,USDNGN=X:USD-NGN,USDBRL=X:USD-BRL,USDAED=X:USD-AED,USDTWD=X:USD-TWD,USDARS=X:USD-ARS foreignscraper -foreignType=YahooFinance
INFO[0000] INFLUXURL: http://data-influx.default.svc.cluster.local:8086 
INFO[0000] Foreign Scraper: Start scraping data from YahooFinance 
INFO[0000] Default update …
```
=> update endpoints for yahoo foreign scraper

config/Curvefi.json, deployments/k8s-yaml/scraper-dex-curve.yaml, testenv.sh
=> Fix the testenv.sh script

pkg/dia/scraper/exchange-scrapers/CurvefiScraper.go
This is the only case we need to look into the AddLiquidity event to find the actual amount sold.
https://github.com/diadata-org/diadata/issues/741
=> CurveFi: Fix underlying coin values when soldID>0

cmd/interlay/bifrosthelper.js, cmd/interlay/cron.js, cmd/interlay/index.js, cmd/interlay/utils.js
=> Add bifrost token

cmd/blockchain/ethereum/diaOracleV2MultiupdateService/main.go
- added backup rpc node for diaOracleV2MultiUpdateService
- backup connection and contract used when primary fails for oracle updates
=> use backup rpc node if primary fails

pkg/dia/scraper/exchange-scrapers/BinanceScraper.go
Description
- add websocket-based scraper for Binance 
InfluxDB screenshot (updated on March 31st):
select * from trades where time < now() and time > now() - 10m
=> Add New Binance Scraper 

config/Binance.json, config/Binance2.json
Remove old pairs from Binance scrapers that are not in use
=> remove old pairs

config/Binance3.json
Description:
- add only one exchange pair in Binance3.json
=> Add Binance3.json for BinanceScraper Testing in Prod

config/CoinEx.json, config/exchanges/exchanges.json, pkg/dia/Config.go, pkg/dia/scraper/exchange-scrapers/APIScraper.go, pkg/dia/scraper/exchange-scrapers/CoinExScraper.go
Description:
- add CoinEx scraper
InfluxDB screenshot (updated on April 4th):
select * from trades where time < now() and time > now() - 10m
=> Add CoinEx Scraper
